# Generated by Django 3.2.2 on 2021-05-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20210507_2343"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authmessage",
            old_name="date",
            new_name="creation_date",
        ),
    ]
